name: FunniewarsDetector
version: '${project.version}'
main: me.cooleg.funniewarsdetector.FunniewarsDetector
api-version: '1.18'
commands:
  funniewarsdetector:
    permission: funniewarsdetector.command

permissions:
  funniewarsdetector.alert:
    default: false